#!/usr/bin/env python3
"""Bridge OpenWork skills into Claude Code desktop skill zips.

OpenWork (`<repo>/.agents/skills`) is the source of truth. This regenerates
`<repo>/.claude/skills` so it contains ONLY one `<skill>.zip` per skill — the
format the Claude Code desktop app imports. Each zip contains the skill folder
nested inside it (unzipping yields `<skill>/SKILL.md`, not a bare SKILL.md),
with these transforms applied to the bundled files:

  1. Tool-name namespace: OpenCode exposes MCP tools as `<server>_<tool>`
     (e.g. `itastack_openwork_config_get_status`); Claude Code exposes them as
     `mcp__<server>__<tool>`. We rewrite the known server prefixes.
  2. Route sentinels: strip OpenWork's `<<<ROUTE ...>>>` tier-routing lines,
     which are meaningless in Claude Code.

This is a one-way, add/update/delete mirror: `.claude/skills` is treated as a
generated artifact and fully rebuilt each run. Zips are always rebuilt fresh
from the source (never unzipped/patched), and are written deterministically
(stable file order + fixed timestamps) so unchanged skills produce byte-identical
zips and clean git diffs. Author skills only in `.agents/skills`.

Usage:
  python3 bridge_skills.py            # regenerate .claude/skills zips
  python3 bridge_skills.py --dry-run  # report what would change, write nothing
  python3 bridge_skills.py --repo /path/to/repo
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
import zipfile
from pathlib import Path

# --- config ----------------------------------------------------------------

# OpenCode server-name prefix -> Claude Code MCP namespace.
# NOTE: validate against the live tool list once the MCP servers load in Cowork
# (ask Claude to list mcp__itastack__* tools) and adjust if the exact names differ.
TOOL_PREFIX_MAP = {
    "itastack_": "mcp__itastack__",
    "testytech_": "mcp__testytech__",
}
TOOL_PATTERNS = [
    (re.compile(r"\b" + re.escape(src)), dst) for src, dst in TOOL_PREFIX_MAP.items()
]

# Match the ROUTE sentinel line plus any blank lines immediately following it,
# so stripping it doesn't leave a run of blank lines behind.
ROUTE_LINE = re.compile(r"^[ \t]*<<<ROUTE\b.*?>>>[ \t]*$", re.MULTILINE)
ROUTE_BLOCK = re.compile(r"^[ \t]*<<<ROUTE\b.*?>>>[ \t]*\n(?:[ \t]*\n)*", re.MULTILINE)

EXCLUDE_DIRS = {".venv", "__pycache__", "node_modules", ".git"}
EXCLUDE_FILES = {".DS_Store"}
EXCLUDE_SUFFIXES = {".pyc"}
TEXT_SUFFIXES = {".md", ".markdown", ".txt"}

GEN_NOTE = (
    "<!-- AUTO-GENERATED by sync-cowork-skills from {src}. "
    "Do not edit here; edit the .agents/skills source and re-run the sync. -->"
)


# --- helpers ---------------------------------------------------------------

def find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / "AGENTS.md").exists() or (p / ".git").exists():
            return p
    raise SystemExit("ERROR: could not locate repo root (no AGENTS.md or .git found).")


def excluded(path: Path) -> bool:
    if any(part in EXCLUDE_DIRS for part in path.parts):
        return True
    if path.name in EXCLUDE_FILES:
        return True
    if path.suffix in EXCLUDE_SUFFIXES:
        return True
    return False


def rewrite_tools(text: str) -> tuple[str, int]:
    total = 0
    for pat, repl in TOOL_PATTERNS:
        text, n = pat.subn(repl, text)
        total += n
    return text, total


def strip_route(text: str) -> tuple[str, int]:
    n = len(ROUTE_LINE.findall(text))
    return ROUTE_BLOCK.sub("", text), n


def transform_markdown(text: str, rel_src: str) -> tuple[str, int, int]:
    text, routes = strip_route(text)
    text, tools = rewrite_tools(text)
    # Insert the generated note right after YAML frontmatter, else at the top.
    note = GEN_NOTE.format(src="/.agents/skills/" + rel_src)
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            close = text.find("\n", end + 1)
            close = len(text) if close == -1 else close
            text = text[:close] + "\n" + note + text[close:]
        else:
            text = note + "\n" + text
    else:
        text = note + "\n" + text
    return text, tools, routes


# --- zip build -------------------------------------------------------------

# Fixed timestamp for every zip entry so unchanged skills produce byte-identical
# zips (1980-01-01 00:00:00 is the minimum a ZIP DOS timestamp can encode).
ZIP_MTIME = (1980, 1, 1, 0, 0, 0)


def build_skill_bytes(skill: str, files: list[Path], src_root: Path) -> tuple[bytes, int, int, int]:
    """Return (zip_bytes, n_files, n_tool_rewrites, n_route_strips) for one skill.

    Files are stored under a top-level `<skill>/` folder inside the zip, in
    sorted order with a fixed timestamp, so the archive is deterministic.
    """
    import io

    n_tools = n_routes = n_files = 0
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for src in sorted(files, key=lambda p: p.relative_to(src_root).as_posix()):
            rel = src.relative_to(src_root)  # e.g. sync-cowork-skills/SKILL.md
            arcname = rel.as_posix()
            if src.suffix in TEXT_SUFFIXES:
                out, tools, routes = transform_markdown(
                    src.read_text(encoding="utf-8"), str(rel)
                )
                n_tools += tools
                n_routes += routes
                data = out.encode("utf-8")
            else:
                data = src.read_bytes()
            info = zipfile.ZipInfo(arcname, date_time=ZIP_MTIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, data)
            n_files += 1
    return buf.getvalue(), n_files, n_tools, n_routes


# --- main ------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", type=Path, default=None, help="repo root (auto-detected by default)")
    ap.add_argument("--dry-run", action="store_true", help="report only, write nothing")
    args = ap.parse_args()

    repo = (args.repo or find_repo_root(Path(__file__).resolve())).resolve()
    src_root = repo / ".agents" / "skills"
    dst_root = repo / ".claude" / "skills"
    if not src_root.is_dir():
        raise SystemExit(f"ERROR: source skills dir not found: {src_root}")

    files = [p for p in src_root.rglob("*") if p.is_file() and not excluded(p)]

    # Group files by their top-level entry. A valid skill is a *directory*
    # containing a SKILL.md; loose files at the skills root and directories
    # without a SKILL.md are not skills and must not become zips.
    grouped: dict[str, list[Path]] = {}
    loose_root_files: list[str] = []
    for p in files:
        rel = p.relative_to(src_root)
        if len(rel.parts) == 1:
            # A file sitting directly in .agents/skills/, not inside a skill dir.
            loose_root_files.append(rel.as_posix())
            continue
        grouped.setdefault(rel.parts[0], []).append(p)

    by_skill: dict[str, list[Path]] = {}
    missing_skill_md: list[str] = []
    for skill, skill_files in grouped.items():
        if any(f.name == "SKILL.md" for f in skill_files):
            by_skill[skill] = skill_files
        else:
            missing_skill_md.append(skill)

    warnings: list[str] = []
    for name in sorted(loose_root_files):
        warnings.append(f"  skipped loose file at skills root (not a skill): {name}")
    for skill in sorted(missing_skill_md):
        warnings.append(f"  skipped '{skill}/' (no SKILL.md — not a valid skill)")

    n_skills = len(by_skill)
    n_files = n_tools = n_routes = 0
    plan: list[str] = []

    if not args.dry_run:
        # Replace .claude/skills wholesale (handles the old symlink/loose files).
        if dst_root.is_symlink() or dst_root.is_file():
            dst_root.unlink()
        elif dst_root.is_dir():
            shutil.rmtree(dst_root)
        dst_root.mkdir(parents=True, exist_ok=True)

    for skill in sorted(by_skill):
        data, files_in, tools, routes = build_skill_bytes(skill, by_skill[skill], src_root)
        n_files += files_in
        n_tools += tools
        n_routes += routes
        plan.append(
            f"  {skill}.zip  ({files_in} files, +{tools} tool refs, -{routes} route lines)"
        )
        if not args.dry_run:
            (dst_root / f"{skill}.zip").write_bytes(data)

    mode = "DRY-RUN (nothing written)" if args.dry_run else "wrote"
    print(f"{mode}: {n_skills} skill zips ({n_files} files bundled)")
    print(f"  tool-name rewrites: {n_tools}")
    print(f"  route sentinels stripped: {n_routes}")
    print(f"  source: {src_root}")
    print(f"  target: {dst_root} (zips only)")
    if plan:
        print("skills:")
        print("\n".join(plan))
    if warnings:
        print("warnings:")
        print("\n".join(warnings))
    return 0


if __name__ == "__main__":
    sys.exit(main())
